version: '3.8'

services:
  backend:
    image: daewoongkim/ts-crud-backend:latest
    container_name: typescript-crud-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  frontend:
    image: daewoongkim/ts-crud-frontend:latest
    container_name: typescript-crud-frontend
    restart: always
    ports:
      - "3001:80"

  mongo:
    image: mongo:6
    container_name: typescript-crud-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
