openapi: 3.0.3                             # OpenAPI spec version (OpenAPI 사양 버전)
info:                                      # API metadata (API 메타데이터)
  title: Post CRUD API                     # API title (API 제목)
  version: 1.0.0                           # API version (API 버전)

paths:                                     # API endpoints (API 경로)
  /api/posts:                              # Posts collection (게시글 컬렉션)
    post:                                  # Create a post (게시글 생성)
      summary: Create a new post (게시글 생성)    # Brief description (간단 설명)
      requestBody:                         # Request body (요청 바디)
        required: true                     # Required (필수)
        content:
          application/json:                # JSON payload (JSON 페이로드)
            schema:
              type: object                 # Object type (객체 타입)
              required:
                - title
                - content
              properties:
                title:
                  type: string             # Post title (게시글 제목)
                content:
                  type: string             # Post content (게시글 내용)
      responses:                           # Possible responses (가능한 응답)
        '201':
          description: Created (생성 성공)    # Success status (성공 상태)
        '400':
          description: Bad Request (잘못된 요청)

    get:                                   # List all posts (전체 게시글 조회)
      summary: List posts (게시글 목록 조회)     # Brief description (간단 설명)
      responses:
        '200':
          description: OK (정상 조회)        # Success status (성공 상태)

  /api/posts/{id}:                         # Single post by ID (ID로 단일 게시글)
    parameters:                            # Path parameter (경로 매개변수)
      - name: id
        in: path
        required: true
        schema:
          type: string                     # ID as string (문자열 ID)

    get:                                   # Get a post by ID (ID로 게시글 조회)
      summary: Get a single post (단일 게시글 조회)  # Brief description (간단 설명)
      responses:
        '200':
          description: OK (정상 조회)
        '404':
          description: Not Found (게시글 없음)

    put:                                   # Update a post by ID (ID로 게시글 수정)
      summary: Update a post by ID (게시글 수정)     # Brief description (간단 설명)
      requestBody:
        required: true                     # Required (필수)
        content:
          application/json:
            schema:
              type: object                 # Object type (객체 타입)
              properties:
                title:
                  type: string             # New title (새 제목)
                content:
                  type: string             # New content (새 내용)
      responses:
        '200':
          description: OK (수정 성공)       # Success status (성공 상태)
        '400':
          description: Bad Request (잘못된 요청)
        '404':
          description: Not Found (게시글 없음)

    delete:                                # Delete a post by ID (ID로 게시글 삭제)
      summary: Delete a post by ID (게시글 삭제)     # Brief description (간단 설명)
      responses:
        '204':
          description: No Content (삭제 성공)   # No payload (본문 없음)
        '404':
          description: Not Found (게시글 없음)
