openapi: 3.0.3                                      # OpenAPI spec version (OpenAPI 사양 버전)
info:                                               # API metadata (API 메타데이터)
  title: Post CRUD API                              # API title (API 제목)
  version: 1.0.0                                    # API version (API 버전)
servers:
  - url: http://localhost:3000                      # Local server URL (로컬 서버 URL)

paths:                                              # API endpoints (API 경로)
  /api/posts:                                       # Posts collection (게시글 컬렉션)
    post:
      summary: Create a new post (게시글 생성)         # Brief description (간단 설명)
      requestBody:
        $ref: '#/components/requestBodies/NewPost'   # Reuse NewPost schema (NewPost 스키마 재사용)
      responses:
        '201':
          $ref: '#/components/responses/PostCreated' # PostCreated response (생성 성공 응답)
        '400':
          $ref: '#/components/responses/BadRequest'   # BadRequest response (잘못된 요청 응답)

    get:
      summary: List posts (게시글 목록 조회)           # Brief description (간단 설명)
      responses:
        '200':
          $ref: '#/components/responses/PostsList'    # PostsList response (목록 응답)

  /api/posts/{id}:                                  # Single post by ID (ID로 단일 게시글)
    parameters:
      - $ref: '#/components/parameters/PostId'       # Reuse PostId parameter (PostId 매개변수 재사용)

    get:
      summary: Get a single post (단일 게시글 조회)    # Brief description (간단 설명)
      responses:
        '200':
          $ref: '#/components/responses/SinglePost'   # SinglePost response (단일 응답)
        '404':
          $ref: '#/components/responses/NotFound'     # NotFound response (찾을 수 없음 응답)

    put:
      summary: Update a post by ID (게시글 수정)        # Brief description (간단 설명)
      requestBody:
        $ref: '#/components/requestBodies/UpdatePost' # Reuse UpdatePost schema (UpdatePost 스키마 재사용)
      responses:
        '200':
          $ref: '#/components/responses/SinglePost'   # SinglePost response (단일 응답)
        '400':
          $ref: '#/components/responses/BadRequest'   # BadRequest response (잘못된 요청 응답)
        '404':
          $ref: '#/components/responses/NotFound'     # NotFound response (찾을 수 없음 응답)

    delete:
      summary: Delete a post by ID (게시글 삭제)         # Brief description (간단 설명)
      responses:
        '204':
          description: No Content (삭제 성공)            # No payload (본문 없음)
        '404':
          $ref: '#/components/responses/NotFound'     # NotFound response (찾을 수 없음 응답)

components:
  schemas:                                           # Data models (데이터 모델)
    Post:
      type: object
      properties:
        _id:
          type: string                                # Post ID (게시글 ID)
        title:
          type: string                                # Post title (게시글 제목)
        content:
          type: string                                # Post content (게시글 내용)
        createdAt:
          type: string
          format: date-time                           # Creation timestamp (생성 시간)
        updatedAt:
          type: string
          format: date-time                           # Update timestamp (수정 시간)

  parameters:                                        # Reusable parameters (재사용 매개변수)
    PostId:
      name: id
      in: path
      required: true
      schema:
        type: string                                  # ID as string (문자열 ID)
      description: ID of the post (게시글 ID)

  requestBodies:                                     # Reusable request bodies (재사용 요청 바디)
    NewPost:
      required: true
      content:
        application/json:
          schema:
            type: object
            required: [title, content]               # Both fields required (두 필드 모두 필수)
            properties:
              title:
                type: string                         # New post title (새 게시글 제목)
              content:
                type: string                         # New post content (새 게시글 내용)

    UpdatePost:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string                         # Updated title (수정된 제목)
              content:
                type: string                         # Updated content (수정된 내용)

  responses:                                         # Reusable responses (재사용 응답)
    PostCreated:
      description: Post created successfully (생성 성공) # Description only (설명만)
      content:
        application/json:
          schema:
            type: object
            properties:
              post:
                $ref: '#/components/schemas/Post'      # Returns new Post (새 게시글 반환)

    PostsList:
      description: List of posts (게시글 목록)           # Description only (설명만)
      content:
        application/json:
          schema:
            type: object
            properties:
              posts:
                type: array
                items:
                  $ref: '#/components/schemas/Post'    # Array of Post (게시글 배열)

    SinglePost:
      description: A single post (단일 게시글)            # Description only (설명만)
      content:
        application/json:
          schema:
            type: object
            properties:
              post:
                $ref: '#/components/schemas/Post'      # Single Post (단일 게시글)

    BadRequest:
      description: Bad Request (잘못된 요청)              # Description only (설명만)
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string                          # Error message (에러 메시지)

    NotFound:
      description: Not Found (찾을 수 없음)               # Description only (설명만)
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string                          # Error message (에러 메시지)
